### ISSUE TITLE
standalone-compilation not working on Raspberry Pi 

### ISSUE THREAD

**Issue by TechStranger** [labstreaminglayer/pylsl#60]
i tried to execute the standalone_compilation_linux.sh on my raspberry pi 3 after cloning the entire sccn/liblsl file into my liblsl-Python/pylsl/lib. However, once i execute the standalone_compilation_linux.sh, a list of error appear. 

*/thirdparty/loguru/loguru.cpp:907:91: error: invalid conversion from 'int' to 'loguru::close_handler_t {aka void (*)(void*)}' [-fpermissive]
thirdparty/loguru/loguru.cpp:907:91: error: invalid conversion from 'loguru::flush_handler_t {aka void (*)(void*)}' to 'unsigned int' [-fpermissive]
thirdparty/loguru/loguru.cpp: At global scope:
thirdparty/loguru/loguru.cpp:913:33: error: redefinition of 'const char* loguru::get_verbosity_name'
  const char* get_verbosity_name(Verbosity verbosity)
                                 ^
In file included from thirdparty/loguru/loguru.cpp:23:0:
thirdparty/loguru/loguru.hpp:593:14: error: 'const char* loguru::get_verbosity_name' previously defined here
  const char* get_verbosity_name(Verbosity verbosity);
              ^
*/ and many other errors

**Comment by tstenner** [comment]
What compiler do you have installed? (`gcc --version`)?

Depending on your environment, some flags might cause problems. Could you run the script with `bash -e standalone_compilation_linux.sh` and paste the full output?

**Comment by cboulay** [comment]
Hi @TechStranger . Another user was having trouble in #68 but with some discussion they got things working. Given the success there, and lack of updates here, I'm closing this issue.
