### ISSUE TITLE
preparing metadata did not run successfully when downloading lsl

### ISSUE THREAD

**Issue by yyswhsccc** [labstreaminglayer/pylsl#65]
Hi,

I met the following error when downloading pylsl on Windows machine with python 3.10.10:

any suggestions for it?
![IMG_4226](https://user-images.githubusercontent.com/57080732/223295787-4fae23de-917a-41df-9abf-b763c4410dc9.JPG)
![IMG_4227](https://user-images.githubusercontent.com/57080732/223295792-d88231be-677d-4944-a147-ed6e96490946.JPG)

Thanks!

**Comment by cboulay** [comment]
I don't know what the python package `lsl` is but it's not this project.

`pip install pylsl`
