### ISSUE TITLE
LSL binary library file was not found on raspberry pi 

### ISSUE THREAD

**Issue by Boris870315** [labstreaminglayer/pylsl#68]
This is the original issue. 
LSL binary library file was not found. Please make sure that the binary file can be found in the package lib folder (/home/boris/.local/lib/python3.9/site-packages/pylsl/lib) or the system search path.

standalone_compilation_linux.sh is not working on my pi. thus, i use pip install pylsl.
$ mv $SITE_PACKAGES/pylsl/lib $SITE_PACKAGES/pylsl/liblsl.so
$ mkdir $SITE_PACKAGES/pylsl/lib
$ mv $SITE_PACKAGES/pylsl/liblsl.so $SITE_PACKAGES/pylsl/lib
I also tried this three comments on my pi, but also not working.

**Comment by cboulay** [comment]
>standalone_compilation_linux.sh is not working on my pi

Let's fix this. What kind of Raspberry Pi? What OS?

```
$ mv $SITE_PACKAGES/pylsl/lib $SITE_PACKAGES/pylsl/liblsl.so
$ mkdir $SITE_PACKAGES/pylsl/lib
$ mv $SITE_PACKAGES/pylsl/liblsl.so $SITE_PACKAGES/pylsl/lib
```

I have no idea what that's doing. It doesn't look right to me. Let's focus on enabling you to build liblsl.so on your pi.

**Comment by Boris870315** [comment]
my raspberry pi system is Raspberry os (64bit) and the version is Raspberry Pi 4.

**Comment by Boris870315** [comment]
https://drive.google.com/file/d/1dIiRcyaoLjfC6xQq1Qblz_eudV2W6dd_/view?usp=sharing
Is this what you want?

**Comment by cboulay** [comment]
No. Please paste the output of `gcc --version`.
Also please paste the output of `bash -e standalone_compilation_linux.sh`

**Comment by Boris870315** [comment]
boris@raspberrypi:~ $ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

boris@raspberrypi:~ $ bash -e standalone_compilation_linux.sh
bash: standalone_compilation_linux.sh: No such file or directory

**Comment by cboulay** [comment]
```
git clone https://github.com/sccn/liblsl.git
cd liblsl
bash -e standalone_compilation_linux.sh
```

**Comment by Boris870315** [comment]
still not working, jupyter is showing the same issue

**Comment by cboulay** [comment]
Forget the `bash -e` part.
If you cd into the liblsl directory that you just cloned, and then run `./standalone_compilation_linux.sh`, what happens?

None of the Python / Jupyter errors matter. All that matters right now is running that script.

**Comment by Boris870315** [comment]
+ git describe --tags HEAD
+ echo v1.16.1-1-g702ebe73
v1.16.1-1-g702ebe73
+ g++ -fPIC -fvisibility=hidden -O2 -Ilslboost -DBOOST_ALL_NO_LIB -DASIO_NO_DEPRECATED -DLOGURU_DEBUG_LOGGING=0 -DLSL_LIBRARY_INFO_STR="v1.16.1-1-g702ebe73" src/api_config.cpp src/buildinfo.cpp src/cancellation.cpp src/common.cpp src/consumer_queue.cpp src/data_receiver.cpp src/info_receiver.cpp src/inlet_connection.cpp src/lsl_inlet_c.cpp src/lsl_outlet_c.cpp src/lsl_resolver_c.cpp src/lsl_streaminfo_c.cpp src/lsl_xml_element_c.cpp src/netinterfaces.cpp src/resolve_attempt_udp.cpp src/resolver_impl.cpp src/sample.cpp src/send_buffer.cpp src/socket_utils.cpp src/stream_info_impl.cpp src/stream_outlet_impl.cpp src/tcp_server.cpp src/time_postprocessor.cpp src/time_receiver.cpp src/udp_server.cpp src/util/cast.cpp src/util/endian.cpp src/util/inireader.cpp src/util/strfuns.cpp thirdparty/pugixml/pugixml.cpp -Ithirdparty/pugixml thirdparty/loguru/loguru.cpp -Ithirdparty/loguru -Ithirdparty/asio lslboost/serialization_objects.cpp -shared -o liblsl.so -lpthread -lrt -ldl
+ gcc -O2 -Iinclude testing/lslver.c -o lslver -L. -llsl
+ LD_LIBRARY_PATH=. ./lslver
LSL version: 116
v1.16.1-1-g702ebe73
16544.123067



it show like this

**Comment by Boris870315** [comment]
thanks, it works now
