### ISSUE TITLE
Changing outlet channel count without closing the process

### ISSUE THREAD

**Issue by AntonelloBS** [labstreaminglayer/pylsl#78]
Hello,
is there a way to update the channel count of a stream without having to stop a process?
I am working on a GUI that let's change some device parameters (channel count and sampling rate) of a device. When I do that I would like to be able to change the outlet parameters without closing it or, if the latter is not possible, to close the outlet and open another one but when I call outlet.__del__() the process stops without giving any error (is this an expected behaviour?)

Thanks in advance for the help

**Comment by cboulay** [comment]
You cannot change a stream's primary metadata after it is created. You have to close it and create a new stream.

I don't know what `outlet.del()` is -- I would expect that to raise an attribute error.
Or do you mean `del outlet`?
