### ISSUE TITLE
Python3.12?

### ISSUE THREAD

**Issue by cogullrich** [labstreaminglayer/pylsl#80]
Anyone get this to work with python 3.12? I'm using OSX and have no issues at all with python 3.9. I recently switched to 3.12 because of another issue and can't get pylsl to load the dynamic library no matter what I do.

**Comment by cboulay** [comment]
Which MacOS?
Which architecture, x86 or ARM?

**Comment by cboulay** [comment]
It's working fine on the GitHub Actions runner for MacOS for Python 3.9-3.12.

Try using the GHA script as a guide for how to setup your environment:
https://github.com/labstreaminglayer/pylsl/blob/main/.github/workflows/ci.yml
